# Tomcat配置
server:
    tomcat:
        uri-encoding: UTF-8
      # 后端服务器的端口8082
    port: 8082
    servlet:
        # 设置应用的上下文路径为/resumeDelivery
        context-path: /resumeDelivery

spring:
    # 数据库mysql配置
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/recruit?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
        username: root
        password: 123456
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    # 静态资源位置
    resources:
      static-locations: classpath:static/,file:static/

# mybatisplus的配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.entity
  global-config:
    id-type: 1
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

# openai api key and 代理服务器
# 这里填写有额度的openai api key以及你的代理服务器的ip和端口，这边是本人clash相关配置
openai:
  api:
    key: sk-proj-6IOLDP4CdKVehLxLTCTyT3BlbkFJeSJDz6VvnCO8kaTcDQgi
proxy:
  host: 127.0.0.1
  port: 55490